- name: Jenkins CI | Check users are provisioned
  command: test -f {{jenkins_install_dir}}/users/deploy/config.xml
  ignore_errors: yes
  register: jenkins_users_present
  become: yes
  become_user: jenkins

- name: Jenkins | Create User groovy Script
  template: src="{{role_dir}}/files/jenkins/create-user.groovy.j2" dest="/var/lib/jenkins/create-user.groovy"
  when: jenkins_users_present|failed
  become: yes
  become_user: jenkins

- name: Jenkins | Create Users
  uri:
    user: admin
    password: "{{ jenkins_admin_password }}"
    force_basic_auth: yes
    body: "script=$(</var/lib/jenkins/create-user.groovy {{item.name}} {{item.password}} {{item.email}})"
    url: "http://127.0.0.1:8080/scriptText?{{ jenkins_crumb_token }}"
    method: POST
    status_code: [200, 302]
  with_items: jenkins_users
  when: jenkins_users is defined and jenkins_users_present|failed
  ignore_errors: yes
  become: yes
  become_user: jenkins

- name: Jenkins | Forced restart
  service: name=jenkins state=restarted
  when: jenkins_users_present|failed
  become: yes


- wait_for: port=8080 delay=20
  when: jenkins_users_present|failed
